
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STORE = 12;
  public static final int ENTERO = 23;
  public static final int DIFERENTE = 28;
  public static final int DOS_PUNTOS = 44;
  public static final int CORCHETE_C = 42;
  public static final int TIPO_STRING = 18;
  public static final int FILTER = 11;
  public static final int ASTERISCO = 47;
  public static final int CORCHETE_A = 41;
  public static final int LLAVE_C = 38;
  public static final int UPDATE = 7;
  public static final int LLAVE_A = 37;
  public static final int TIPO_ARRAY = 19;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int IGUAL = 36;
  public static final int USE = 3;
  public static final int OR = 34;
  public static final int PUNTO_COMA = 43;
  public static final int IGUAL_IGUAL = 27;
  public static final int ID = 26;
  public static final int EOF = 0;
  public static final int DECIMAL = 24;
  public static final int TABLE = 4;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int NULO = 21;
  public static final int EXPORT = 9;
  public static final int CADENA = 25;
  public static final int ADD = 6;
  public static final int MENOR = 32;
  public static final int FIELDS = 10;
  public static final int TIPO_INT = 15;
  public static final int MAYOR = 31;
  public static final int TIPO_OBJECT = 20;
  public static final int PUNTO = 46;
  public static final int READ = 5;
  public static final int MAYOR_IGUAL = 29;
  public static final int CLEAR = 8;
  public static final int DATABASE = 2;
  public static final int TIPO_FLOAT = 16;
  public static final int TIPO_BOOL = 17;
  public static final int BOOLEANO = 22;
  public static final int PAREN_C = 40;
  public static final int PAREN_A = 39;
  public static final int AT = 13;
  public static final int MENOR_IGUAL = 30;
  public static final int SET = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATABASE",
  "USE",
  "TABLE",
  "READ",
  "ADD",
  "UPDATE",
  "CLEAR",
  "EXPORT",
  "FIELDS",
  "FILTER",
  "STORE",
  "AT",
  "SET",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_BOOL",
  "TIPO_STRING",
  "TIPO_ARRAY",
  "TIPO_OBJECT",
  "NULO",
  "BOOLEANO",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "AND",
  "OR",
  "NOT",
  "IGUAL",
  "LLAVE_A",
  "LLAVE_C",
  "PAREN_A",
  "PAREN_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMA",
  "PUNTO",
  "ASTERISCO"
  };
}

